language: c++

install:
  - sudo apt-get update
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository --yes 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main'
  - sudo apt-get update
  - sudo apt-get install clang-3.5 clang-3.5-doc libclang-common-3.5-dev libclang-3.5-dev libclang1-3.5 libclang1-3.5-dbg libllvm3.5 libllvm3.5-dbg llvm-3.5 llvm-3.5-dev llvm-3.5-doc llvm-3.5-examples llvm-3.5-runtime clang-modernize-3.5 clang-format-3.5 python-clang-3.5 libedit-dev
  - sudo ln -s /usr/bin/clang-3.5 /usr/bin/clang
  - sudo ln -s /usr/bin/clang++-3.5 /usr/bin/clang++

script:
  - make
  - make test
